#!/usr/bin/env bash
# Package the extensions into dist/ for both browsers.
set -euo pipefail
cd "$(dirname "$0")/.."
version="$(python3 -c 'import json;print(json.load(open("extension/manifest.json"))["version"])')"
mkdir -p dist

firefox_out="dist/BiliWebAndroidStream-firefox-v${version}-unsigned.zip"
rm -f "$firefox_out"
(cd extension && zip -qr "../${firefox_out}" .)
echo "built ${firefox_out}"

# Chrome build: MV3 manifest plus a single concatenated service worker
# (MV3 backgrounds do not support a script list like Firefox does).
chrome_tree="$(mktemp -d)"
trap 'rm -rf "$chrome_tree"' EXIT
cp -r extension/. "$chrome_tree/"
mv "$chrome_tree/manifest.chrome.json" "$chrome_tree/manifest.json"
python3 - "$version" "$chrome_tree" <<'EOF'
import json, pathlib, sys
version, tree = sys.argv[1], pathlib.Path(sys.argv[2])
manifest = json.loads((tree / 'manifest.json').read_text())
manifest['version'] = version
(tree / 'manifest.json').write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + '\n')
src = tree / 'src'
parts = [
    '// Chrome service worker bundle: generated by scripts/build.sh.\n',
    (src / 'lib/md5.js').read_text(),
    (src / 'lib/qrcode.js').read_text(),
    (src / 'native-api.js').read_text(),
    (src / 'background.js').read_text(),
]
(src / 'background-chrome.js').write_text('\n;\n'.join(p.rstrip() + '\n' for p in parts))
EOF
chrome_out="dist/BiliWebAndroidStream-chrome-v${version}-unsigned.zip"
rm -f "$chrome_out"
(cd "$chrome_tree" && zip -qr "$OLDPWD/${chrome_out}" .)
echo "built ${chrome_out}"
